APP:
  API_KEY : "6c1118aa11d0d1944adf85aa86602b5ee47da646"
  APP_NAME : "Dot Tes"
  APP_DOMAIN : ""
  MY_PACKAGE : "dot-be"
  MY_PORT : 9003
  MY_URL : "http://127.0.0.1:9003"
  VERSION : 1.0
  SHOW_LOG : false
  IS_PRODUCTION : false
  JWT_SECRET : "f502a59fef2633cfc755d5725e5e853135f0fa52"
  JWT_REFRESH_SECRET : "53cce2afbdb76b970650590dc0250e2c3a99a581"
  LOGIN_EXPIRATION_DURATION : 24
  MAINTENANCE : false
  MSG_MAINTENANCE : "Server Sedang Maintenance"

MYSQL :
  MYSQL_HOST_WRITE : "127.0.0.1"
  MYSQL_USER_WRITE : "root"
  MYSQL_PASS_WRITE : "12345678"
  MYSQL_PORT_WRITE : 3306
  MYSQL_DB_NAME : "db_dot_test"

REDIS :
  REDIS_HOST_LOCAL : "127.0.0.1"
  REDIS_PORT_LOCAL : 6379
  REDIS_PASS_LOCAL : ""